### ISSUE TITLE
Error trying to delete a source study

### ISSUE THREAD

**Issue by frano-m** [clevercanary/hca-atlas-tracker#297]
I sometimes experience an error when deleting a source study. I am * usually *, able to replicate the error if I follow these steps:

1. run local.
2. add new source study.
3. build local.
4. try to delete newly added source study.

I'm not certain this is the reason for the error, but perhaps logging out / logging in or something to that effect???

```
[sourceStudyId]-534da68b99105b55.js:28 Uncaught (in promise) Error: error: update or delete on table "source_studies" violates foreign key constraint "fk_source_datasets_source_study_id" on table "source_datasets"
```

<img width="1379" alt="image" src="https://github.com/clevercanary/hca-atlas-tracker/assets/18710366/f8f1a0de-67f0-4b5e-a7e2-8ed6988456e4">

**Comment by hunterckx** [comment]
Can't check right now but my guess as to what might be happening is that the source study has CELLxGENE datasets that get automatically added when the server starts, and then the study can't be deleted alone because that would leave the datasets with references to a source study that doesn't exist; presumably we'll need to update the source study API to delete the associated source datasets as well

**Comment by hunterckx** [comment]
Okay testing it a bit I *think* the above holds up -- I did think briefly that there was some inconsistent behavior in whether a source study with source datasets could be deleted, but I'm thinking now that the ones that didn't error were shared by multiple atlases and so weren't actually deleted (which does check out in the quick follow-up test I did)

**Comment by NoopDog** [comment]
Complete
